permalink: /:month-:day-:year/:title.html
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge
highlighter: rouge
exclude: [vendor]
sass:
  sass_dir: _scss
  style: compressed
plugins:
  - jekyll-algolia
algolia:
  application_id: 'G160Y1N5OT'
  index_name:     'codeception'  
  read_only_api_key: 'c264188100c4fb7017c4f5702a7d4b8d'
  allowed_extensions:
    - ".markdown"
    - ".html"
  excluded_files:
    - "index.html"
    - "docs-2.0"
    - "docs-1.8"
    - "2012-"
    - "2013-"
    - "2014-"
banner:
  # disable content to show last blogpost
  content: '🎉 Codeception truns 10! <a href="https://calendar.google.com/event?action=TEMPLATE&tmeid=OThib3BkM2ViaWlxbmgwcXViaGc0cDFwMDQgZGF2ZXJ0LnVhQG0&tmsrc=davert.ua%40gmail.com">Join online celebration</a> on November 30!'
  # content: '<a href="https://opencollective.com/codeception">Codeception is on OpenCollective! Support us 💖</a>'
