permalink: /:month-:day-:year/:title.html
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge
highlighter: rouge
exclude: [vendor]
plugins:
  - algoliasearch-jekyll
algolia:
  application_id: 'G160Y1N5OT'
  index_name:     'codeception'  
  read_only_api_key: 'c264188100c4fb7017c4f5702a7d4b8d'
  record_css_selector: '.page'  
  excluded_files:
    - index.html
    - slides
    - _posts/2012-*
    - _posts/2013-*
    - _posts/2014-*
    - docs-1.8/*
    - docs-2.0/*