# This is a basic workflow to help you get started with Actions

name: Auto-publish website

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 2 * * 1-6"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}      
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4      

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Build docs
        run: ./vendor/bin/robo build:docs
        
      - name: Publish docs
        run: ./vendor/bin/robo publish

